name: GitHub Profile Summary Cards

permissions:
  contents: write
  
on:
  schedule: # 자동 업데이트 (매일 새벽 3시)
    - cron: "0 3 * * *"
  workflow_dispatch: # 수동 실행도 가능

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate summary cards
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          # Private 레포지토리를 포함하려면 GITHUB_TOKEN 대신 'repo' 권한이 있는 Personal Access Token(PAT)을 사용해야 합니다.
          # Settings > Secrets > Actions에 GH_TOKEN이라는 이름으로 PAT를 등록하세요.
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          USERNAME: Seung-seop-Lee
          THEME: github_dark
